name: europace-todo
services:
  user-service:
    build: ./../backend/user-service
    container_name: user-service
    ports:
      - "8081:8080"

  todo-service:
    build: ./../backend/todo-service
    container_name: todo-service
    ports:
      - "8082:8080"