name: europace-todo
services:
  user-service:
    build: ./../backend/user-service
    container_name: user-service
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_USER}
      - SPRING_DATASOURCE_USERNAME_USER=${SPRING_DATASOURCE_USERNAME_USER}
      - SPRING_DATASOURCE_PASSWORD_USER=${SPRING_DATASOURCE_PASSWORD_USER}
      - SERVER_PORT_USER=${SERVER_PORT_USER}
    healthcheck:
      test: [ "CMD-SHELL", "curl -k -f http://localhost:8081/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8081:8081"

  todo-service:
    build: ./../backend/todo-service
    container_name: todo-service
    environment:
      - SPRING_DATASOURCE_URL_TODO=${SPRING_DATASOURCE_URL_TODO}
      - SPRING_DATASOURCE_USERNAME_TODO=${SPRING_DATASOURCE_USERNAME_TODO}
      - SPRING_DATASOURCE_PASSWORD_TODO=${SPRING_DATASOURCE_PASSWORD_TODO}
      - SERVER_PORT_TODO=${SERVER_PORT_TODO}
      - USER_SERVICE_BASE_URL=${USER_SERVICE_BASE_URL}
    depends_on:
      - user-service
    healthcheck:
      test: [ "CMD-SHELL", "curl -k -f http://localhost:8082/todos/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8082:8082"