name: europace-todo
services:
  user-service:
    build: ./../backend/user-service
    container_name: user-service
    healthcheck:
      test: [ "CMD-SHELL", "curl -k -f http://localhost:8080/health/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8081:8081"

  todo-service:
    build: ./../backend/todo-service
    container_name: todo-service
    healthcheck:
      test: [ "CMD-SHELL", "curl -k -f http://localhost:8080/health/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8082:8082"